# Generated by Django 3.1.2 on 2021-04-20 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_photo_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='created_by',
        ),
    ]
